# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-17 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0003_auto_20190417_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveymodel',
            name='content_id',
            field=models.IntegerField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
