# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-18 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0006_auto_20190418_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveymodel',
            name='year',
            field=models.IntegerField(default=2019),
            preserve_default=False,
        ),
    ]
